/*Alertas*/
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

/*Autenticacion: Iniciar Sesion */
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

/*CRUD DE EMPLEADOS*/
export const LISTAR_EMPLEADOS = 'LISTAR_EMPLEADOS';
export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO';
export const VALIDAR_EMPLEADO = 'VALIDAR_EMPLEADO';
export const ACTUAL_EMPLEADO = 'ACTUAL_EMPLEADO';
export const ACTUALIZAR_EMPLEADO = 'ACTUALIZAR_EMPLEADO';
export const ELIMINAR_EMPLEADO = 'ELIMINAR_EMPLEADO';
export const BUSCAR_EMPLEADO = 'BUSCAR_EMPLEADO';
export const LIMPIAR_EMPLEADO_SELECCIONADO= 'LIMPIAR_EMPLEADO_SELECCIONADO';

/*CRUD DE CLIENTES*/
export const LISTAR_CLIENTES = 'LISTAR_CLIENTES';
export const AGREGAR_CLIENTE = 'AGREGAR_CLIENTE';
export const VALIDAR_CLIENTE = 'VALIDAR_CLIENTE';
export const ACTUAL_CLIENTE = 'ACTUAL_CLIENTE';
export const ACTUALIZAR_CLIENTE = 'ACTUALIZAR_CLIENTE';
export const ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE';
export const LIMPIAR_CLIENTE_SELECCIONADO= 'LIMPIAR_CLIENTE_SELECCIONADO';

/*CRUD DE PROVEEDORES*/
export const LISTAR_PROVEEDORES = 'LISTAR_PROVEEDORES';
export const AGREGAR_PROVEEDOR = 'AGREGAR_PROVEEDOR';
export const VALIDAR_PROVEEDOR = 'VALIDAR_PROVEEDOR';
export const ACTUAL_PROVEEDOR = 'ACTUAL_PROVEEDOR';
export const ACTUALIZAR_PROVEEDOR = 'ACTUALIZAR_PROVEEDOR';
export const ELIMINAR_PROVEEDOR = 'ELIMINAR_PROVEEDOR';
export const LIMPIAR_PROVEEDOR_SELECCIONADO= 'LIMPIAR_PROVEEDOR_SELECCIONADO';

/*CRUD DE USUARIOS*/
export const LISTAR_USUARIOS = 'LISTAR_USUARIOS';
export const SELECT_EMPLEADOS = 'SELECT_EMPLEADOS';
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const VALIDAR_USUARIO = 'VALIDAR_USUARIO';
export const ACTUAL_USUARIO = 'ACTUAL_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const LIMPIAR_USUARIO_SELECCIONADO = 'LIMPIAR_USUARIO_SELECCIONADO';

/*CRUD DE PRODUCTOS*/
export const LISTAR_PRODUCTOS = 'LISTAR_PRODUCTOS';
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const VALIDAR_PRODUCTO = 'VALIDAR_PRODUCTO';
export const ACTUALIZAR_PRODUCTO = 'ACTUALIZAR_PRODUCTO';
export const ACTUAL_PRODUCTO = 'ACTUAL_PRODUCTO';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const LIMPIAR_PRODUCTO_SELECCIONADO = 'LIMPIAR_PRODUCTO_SELECCIONADO';

/*CRUD DE CATEGORIAS*/
export const LISTAR_CATEGORIAS = 'LISTAR_CATEGORIAS';
export const AGREGAR_CATEGORIA = 'AGREGAR_CATEGORIA';
export const VALIDAR_CATEGORIA = 'VALIDAR_CATEGORIA';
export const ACTUALIZAR_CATEGORIA = 'ACTUALIZAR_CATEGORIA';
export const ACTUAL_CATEGORIA = 'ACTUAL_CATEGORIA';
export const ELIMINAR_CATEGORIA = 'ELIMINAR_CATEGORIA';
export const LIMPIAR_CATEGORIA_SELECCIONADA = 'LIMPIAR_CATEGORIA_SELECCIONADA';

/*CRUD DE BODEGAS*/
export const LISTAR_BODEGAS = 'LISTAR_BODEGAS';
export const AGREGAR_BODEGA = 'AGREGAR_BODEGA';
export const VALIDAR_BODEGA = 'VALIDAR_BODEGA';
export const ACTUALIZAR_BODEGA = 'ACTUALIZAR_BODEGA';
export const ACTUAL_BODEGA = 'ACTUAL_BODEGA';
export const ELIMINAR_BODEGA = 'ELIMINAR_BODEGA';
export const LIMPIAR_BODEGA_SELECCIONADA = 'LIMPIAR_BODEGA_SELECCIONADA';

/*MODULO DE ORDENES DE COMPRAR*/
export const LISTAR_ORDENES_COMPRA = 'LISTAR_ORDENES_COMPRA';
export const AGREGAR_ORDEN_COMPRA = 'AGREGAR_ORDEN_COMPRA';
export const VALIDAR_ORDEN_COMPRA = 'VALIDAR_ORDEN_COMPRA';
export const ACTUAL_ORDEN_COMPRA = 'ACTUAL_ORDEN_COMPRA';
export const ELIMINAR_ORDEN_COMPRA = 'ELIMINAR_ORDEN_COMPRA';
export const LIMPIAR_ORDEN_COMPRA_SELECCIONADA = 'LIMPIAR_ORDEN_COMPRA_SELECCIONADA';
export const PRODUCTOS_ORDEN_COMPRA = 'PRODUCTOS_ORDEN_COMPRA';
export const AGREGAR_PRODUCTO_ORDEN_COMPRA = 'AGREGAR_PRODUCTO_ORDEN_COMPRA';
export const VALIDAR_PRODUCTO_ORDEN_COMPRA = 'VALIDAR_PRODUCTO_ORDEN_COMPRA';
export const ELIMINAR_PRODUCTO_ORDEN_COMPRA = 'ELIMINAR_PRODUCTO_ORDEN_COMPRA';

/*CRUD DE COMPRAS*/
export const LISTAR_COMPRAS = 'LISTAR_COMPRAS';
export const AGREGAR_COMPRA = 'AGREGAR_COMPRA';
export const VALIDAR_COMPRA = 'VALIDAR_COMPRA';
export const ACTUALIZAR_COMPRA = 'ACTUALIZAR_COMPRA';
export const ACTUAL_COMPRA = 'ACTUAL_COMPRA';
export const ELIMINAR_COMPRA = 'ELIMINAR_COMPRA';
export const LIMPIAR_COMPRA_SELECCIONADA = 'LIMPIAR_COMPRA_SELECCIONADA';
export const ULTIMO_CODIGO_COMPRA = 'ULTIMO_CODIGO_COMPRA';

